name: CI-CD

on: push
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checks out the current git commit so we can use it.
      # read more at https://github.com/orgs/community/discussions/25682
      - uses: actions/checkout@v2

      - name: Install deps
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
